=== Wern-rm/aion-germany/AL-Game/data/static_data/items/grind_combines.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../modifiers.xsd"/>
    <xs:include schemaLocation="../../global_types.xsd"/>
    <xs:element name="grind_combines">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="grind_combine" type="GrindCombine" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="GrindCombine">
        <xs:sequence>
            <xs:element name="reward_grind" type="RewardGrind" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="name" type="xs:string" use="optional"/>
        <xs:attribute name="target_class" type="playerClass" use="required"/>
        <xs:attribute name="category" type="xs:string" use="required"/>
        <xs:attribute name="price" type="xs:int" use="required"/>
        <xs:attribute name="material_color_1" type="xs:int" use="required"/>
        <xs:attribute name="material_color_2" type="xs:int" use="required"/>
        <xs:attribute name="material_quality_1" type="xs:int" use="optional"/>
        <xs:attribute name="material_quality_2" type="xs:int" use="optional"/>
    </xs:complexType>
    <xs:complexType name="RewardGrind">
        <xs:attribute name="item_id" type="xs:int"/>
    </xs:complexType>
</xs:schema>

=== Wern-rm/aion-germany/AL-Game/data/static_data/items/grind_combines.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- parsed by phpTools from Aion Germany Group (Mariella) at 2020-10-31 16:52 -->
<grind_combines xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="grind_combines.xsd">
    <grind_combine id="1" name="odian_fi_rr" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="1">
        <reward_grind item_id="167200011"/>
        <reward_grind item_id="167200012"/>
        <reward_grind item_id="167200083"/>
        <reward_grind item_id="167200084"/>
        <reward_grind item_id="167200155"/>
        <reward_grind item_id="167200156"/>
    </grind_combine>
    <grind_combine id="2" name="odian_fi_rg" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="2">
        <reward_grind item_id="167200035"/>
        <reward_grind item_id="167200036"/>
        <reward_grind item_id="167200107"/>
        <reward_grind item_id="167200108"/>
        <reward_grind item_id="167200179"/>
        <reward_grind item_id="167200180"/>
    </grind_combine>
    <grind_combine id="3" name="odian_fi_rb" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="3">
        <reward_grind item_id="167200059"/>
        <reward_grind item_id="167200060"/>
        <reward_grind item_id="167200131"/>
        <reward_grind item_id="167200132"/>
        <reward_grind item_id="167200203"/>
        <reward_grind item_id="167200204"/>
    </grind_combine>
    <grind_combine id="4" name="odian_fi_gg" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="2" material_color_2="2">
        <reward_grind item_id="167200059"/>
        <reward_grind item_id="167200060"/>
        <reward_grind item_id="167200131"/>
        <reward_grind item_id="167200132"/>
        <reward_grind item_id="167200203"/>
        <reward_grind item_id="167200204"/>
    </grind_combine>
    <grind_combine id="5" name="odian_fi_gb" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="2" material_color_2="3">
        <reward_grind item_id="167200011"/>
        <reward_grind item_id="167200012"/>
        <reward_grind item_id="167200083"/>
        <reward_grind item_id="167200084"/>
        <reward_grind item_id="167200155"/>
        <reward_grind item_id="167200156"/>
    </grind_combine>
    <grind_combine id="6" name="odian_fi_bb" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="3" material_color_2="3">
        <reward_grind item_id="167200035"/>
        <reward_grind item_id="167200036"/>
        <reward_grind item_id="167200107"/>
        <reward_grind item_id="167200108"/>
        <reward_grind item_id="167200179"/>
        <reward_grind item_id="167200180"/>
    </grind_combine>
    <grind_combine id="7" name="odian_fi_rr_11" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="1" material_quality_1="1" material_quality_2="1">
        <reward_grind item_id="167200011"/>
        <reward_grind item_id="167200012"/>
    </grind_combine>
    <grind_combine id="8" name="odian_fi_rg_11" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="2" material_quality_1="1" material_quality_2="1">
        <reward_grind item_id="167200035"/>
        <reward_grind item_id="167200036"/>
    </grind_combine>
    <grind_combine id="9" name="odian_fi_rb_11" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="3" material_quality_1="1" material_quality_2="1">
        <reward_grind item_id="167200059"/>
        <reward_grind item_id="167200060"/>
    </grind_combine>
    <grind_combine id="10" name="odian_fi_rr_33" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="1" material_quality_1="3" material_quality_2="3">
        <reward_grind item_id="167200083"/>
        <reward_grind item_id="167200084"/>
    </grind_combine>
    <grind_combine id="11" name="odian_fi_rg_33" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="2" material_quality_1="3" material_quality_2="3">
        <reward_grind item_id="167200107"/>
        <reward_grind item_id="167200108"/>
    </grind_combine>
    <grind_combine id="12" name="odian_fi_rb_33" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="3" material_quality_1="3" material_quality_2="3">
        <reward_grind item_id="167200131"/>
        <reward_grind item_id="167200132"/>
    </grind_combine>
    <grind_combine id="13" name="odian_fi_rr_55" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="1" material_quality_1="5" material_quality_2="5">
        <reward_grind item_id="167200155"/>
        <reward_grind item_id="167200156"/>
    </grind_combine>
    <grind_combine id="14" name="odian_fi_rg_55" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="2" material_quality_1="5" material_quality_2="5">
        <reward_grind item_id="167200179"/>
        <reward_grind item_id="167200180"/>
    </grind_combine>
    <grind_combine id="15" name="odian_fi_rb_55" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="1" material_color_2="3" material_quality_1="5" material_quality_2="5">
        <reward_grind item_id="167200203"/>
        <reward_grind item_id="167200204"/>
    </grind_combine>
    <grind_combine id="16" name="odian_fi_gg_11" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="2" material_color_2="2" material_quality_1="1" material_quality_2="1">
        <reward_grind item_id="167200059"/>
        <reward_grind item_id="167200060"/>
    </grind_combine>
    <grind_combine id="17" name="odian_fi_gb_11" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="2" material_color_2="3" material_quality_1="1" material_quality_2="1">
        <reward_grind item_id="167200011"/>
        <reward_grind item_id="167200012"/>
    </grind_combine>
    <grind_combine id="18" name="odian_fi_gg_33" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="2" material_color_2="2" material_quality_1="3" material_quality_2="3">
        <reward_grind item_id="167200131"/>
        <reward_grind item_id="167200132"/>
    </grind_combine>
    <grind_combine id="19" name="odian_fi_gb_33" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="2" material_color_2="3" material_quality_1="3" material_quality_2="3">
        <reward_grind item_id="167200083"/>
        <reward_grind item_id="167200084"/>
    </grind_combine>
    <grind_combine id="20" name="odian_fi_gg_55" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="2" material_color_2="2" material_quality_1="5" material_quality_2="5">
        <reward_grind item_id="167200203"/>
        <reward_grind item_id="167200204"/>
    </grind_combine>
    <grind_combine id="21" name="odian_fi_gb_55" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="2" material_color_2="3" material_quality_1="5" material_quality_2="5">
        <reward_grind item_id="167200155"/>
        <reward_grind item_id="167200156"/>
    </grind_combine>
    <grind_combine id="22" name="odian_fi_bb_11" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="3" material_color_2="3" material_quality_1="1" material_quality_2="1">
        <reward_grind item_id="167200035"/>
        <reward_grind item_id="167200036"/>
    </grind_combine>
    <grind_combine id="23" name="odian_fi_bb_33" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="3" material_color_2="3" material_quality_1="3" material_quality_2="3">
        <reward_grind item_id="167200107"/>
        <reward_grind item_id="167200108"/>
    </grind_combine>
    <grind_combine id="24" name="odian_fi_bb_55" target_class="GLADIATOR" category="ODIAN" price="50000" material_color_1="3" material_color_2="3" material_quality_1="5" material_quality_2="5">
        <reward_grind item_id="167200179"/>
        <reward_grind item_id="167200180"/>
    </grind_combine>
    <grind_combine id="25" name="odian_kn_rr" target_class="TEMPLAR" category="ODIAN" price="50000" material_color_1="1" material_color_2="1">
        <reward_grind item_id="167200013"/>
        <reward_grind item_id="167200014"/>
        <reward_grind item_id="167200085"/>
        <reward_grind item_id="167200086"/>
        <reward_grind item_id="167200157"/>
        <reward_grind item_id="167200158"/>
    </grind_combine>
    <grind_combine id="26" name="odian_kn_rg" target_class="TEMPLAR" category="ODIAN" price="50000" material_color_1="1" material_color_2="2">
        <reward_grind item_id="167200037"/>
        <reward_grind item_id="167200038"/>
        <reward_grind item_id="167200109"/>
        <reward_grind item_id="167200110"/>
        <reward_grind item_id="167200181"/>
        <reward_grind item_id="167200182"/>
    </grind_combine>
    <grind_combine id="27" name="odian_kn_rb" target_class="TEMPLAR" category="ODIAN" price="50000" material_color_1="1" material_color_2="3">
        <reward_grind item_id="167200061"/>
        <reward_grind item_id="167200062"/>
        <reward_grind item_id="167200133"/>
        <reward_grind item_id="167200134"/>
        <reward_grind item_id="167200205"/>
        <reward_grind item_id="167200206"/>
    </grind_combine>
    <grind_combine id="28" name="odian_kn_gg" target_class="TEMPLAR" category="ODIAN" price="50000" material_color_1="2" material_color_2="2">
        <reward_grind item_id="167200061"/>
        <reward_grind item_id="167200062"/>
        <reward_grind item_id="167200133"/>
